# Generated by Django 4.2.6 on 2023-10-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='message',
        ),
    ]
